server.port: 8135

spring:
  jta:
    enabled: true
  application:
    name: db-project
  datasource:
    url: jdbc:postgresql://localhost:5432/itmo
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/itmo
    user: postgres
    password: postgres

