logging:
  level:
    root: INFO

server:
  port: 8135

spring:
  jta:
    enabled: true
  application:
    name: db-project
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s308414
    password: pass
  flyway:
    url: jdbc:postgresql://localhost:5432/studs
    user: s308414
    password: pass
